# site settings
title: Pista ng Mapa 2020
description: "a free and open mapping conference in the Philippines"
email: "pistangmapa@gmail.com"
baseurl: "/2020"
logo: "assets/img/site/WFH_Feels_full_bg.webp"
favicon: favicon.ico
repo_address: "pistangmapa/2020"
messenger: ""
facebook: "PistaNgMapa2020"
twitter: "pistangmapa"
instagram: ""
mastodon: "@pistangmapa"
telegram: "pistangmapa"
github: "pistangmapa"

# tito event
tito-event: "pnm/2020-cebu"


# exclude
exclude:
    - .gitignore
    - Gemfile
    - Gemfile.lock

# build settings
markdown: kramdown
highlighter: rouge
# kramdown:
#     input: GFM
#     syntax_highlighter: rouge

# plugins
plugins:
    - github-pages
    - jekyll-feed
    - jekyll-seo-tag
    - jekyll-sitemap
